sfx:
  realm: us1
  token: xxx
flows:
- name: catchpoint-data
  query: |
    data('catchpoint.counterrequests').publish()
    data('catchpoint.counterfailedrequests').publish()
    data('catchpoint.total.time').publish()
  prometheusMetricTemplate:
    name: "{{ .SignalFxMetricName }}"
    labels:
      probe: '{{ .Meta.CustomProperties.cp_testname }}'
- name: catchpoint-data-5m
  query: |
    data('catchpoint.counterrequests').sum(by=['sf_metric', 'cp_testname']).sum(over='5m').publish()
    data('catchpoint.counterfailedrequests').sum(by=['sf_metric', 'cp_testname']).sum(over='5m').publish()
    data('catchpoint.total.time').median(by=['sf_metric', 'cp_testname']).median(over='5m').publish()
  prometheusMetricTemplate:
    name: "{{ .SignalFxMetricName }}:5m"
    labels:
      probe: '{{ .Meta.CustomProperties.cp_testname }}'
