flows:
- name: raw-catchpoint
  sfx:
    realm: us1
    token: xxx
  query: |
    data('catchpoint.*').sum(by=['sf_metric', 'cp_testname']).publish()
    data('catchpoint.*').sum(by=['sf_metric', 'cp_testname']).sum(over='5m').publish(label='5m')
  selector:
    matchExpressions:
    - key: sf_metric
      operator: In
      values:
      - catchpoint.counterfailedrequests
      - catchpoint.counterrequests
  prometheusMetric:
    name: "{{ .OriginatingMetric }}"
    labels:
      probe: '{{ .CustomProperties.cp_testname }}'
