name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3
      with:
        image: signalfx-prometheus-exporter
        tags: latest ${{ steps.vars.outputs.sha_short }}
        dockerfiles: |
          ./Dockerfile
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@5860fc963bf8f2b3221773a023141612f010c469 # v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/goberlec
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_TOKEN }}
